create database DQL2;
use DQL2;

create table CUSTOMER_DETAILS (
CUSTOMER_ID VARCHAR(10),
CUSTOMER_NAME VARCHAR(30),
PHONE_NO BIGINT(10),
CITY VARCHAR(20));
create table PURCHASE_DETAILS (
PURCHASE_ID VARCHAR(10),
CUSTOMER_ID VARCHAR(10),
PET_ID VARCHAR(5),
PURCHASE_DATE DATE,
TOTAL_AMOUNT_PAID DOUBLES(8,2)
);
create table PET_DETAILS (
PET_ID VARCHAR(10),
PET_NAME VARCHAR(30),
PET_TYPE VARCHAR(10),
BREED VARCHAR(20),
GENDER VARCHAR(10),
AGE_IN_DAYS INT(4),
PRICE DOUBLE(7,2)
);
SELECT CUSTOMER_ID,CUSTOMER_NAME FROM CUSTOMER_DETAILS AND PURCHASE_ID AS N0_OF_PETS WHERE COUNT(PURCHASE_ID) >1  FROM PURCHASE_DETAILS GROUP BY CUSTOMER_NAME ;